# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=10000)),
                ('ps', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('df', models.IntegerField()),
                ('spAtk', models.IntegerField()),
                ('spDef', models.IntegerField()),
                ('spe', models.IntegerField()),
                ('number', models.IntegerField()),
                ('type1', models.CharField(max_length=20)),
                ('type2', models.CharField(max_length=20)),
            ],
        ),
    ]
